#pragma once

#if defined(SETUPCONNECTIONS_DIALOG_LIBRARY)
    #define SETUPCONNECTIONS_DIALOG_SHARED_EXPORT Q_DECL_EXPORT
#else
    #define SETUPCONNECTIONS_DIALOG_SHARED_EXPORT Q_DECL_IMPORT
#endif

