version: "3.3"
services:
  postgres:
    image: postgres:13.3
    container_name:  niokr_archiv_PSQL_13.3
    environment:
      POSTGRES_DB: "niokrDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db_init_scripts:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart:
      always

  nginx:
    image: nginx
    container_name: web_server
    hostname: niokr
    #build: ./volumes/build/nginx
    volumes:
      - ~/SOFT/Github/GIT/16_WEB_ARHIV/CONTENT:/usr/share/nginx/html
      #- ./var/log/nginx:/var/log/nginx #log файлы.
      #- ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro #Конфигурация nginx.
      #- ./volumes/etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro #Конфигурация площадок.
      #- ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro #сертификаты
      #- /var/www/DOMAIN_NAME:/var/www/DOMAIN_NAME #Домашняя директория
    ports:
      - "8080:80"
      - "443:443"
    #links:
      #- php-fpm
    restart:
      always
    #networks:
      #default:
        #ipv4_address: 172.16.1.4
        #ipv4_address: localhost
