#include <utility>
#include <numeric>
#include <climits>
#include <type_traits>

#include <QDir>
#include <array>
#include <QRect>
#include <QDate>
#include <QFile>
#include <QList>
#include <QMenu>
#include <QDebug>
#include <QLabel>
#include <QFrame>
#include <QColor>
#include <QLocale>
#include <QDialog>
#include <QRegExp>
#include <QObject>
#include <QString>
#include <QWidget>
#include <QVariant>
#include <QSplitter>
#include <algorithm>
#include <QSettings>
#include <QComboBox>
#include <QFileInfo>
#include <QDateTime>
#include <QStatusBar>
#include <QByteArray>
#include <QTableView>
#include <QStringList>
#include <QPushButton>
#include <QMessageBox>
#include <QModelIndex>
#include <QMainWindow>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QToolButton>
#include <QTranslator>
#include <QtNetwork/QTcpSocket>
#include <QJsonArray>
#include <QJsonValue>
#include <QJsonObject>
#include <QFileDevice>
#include <QFileDialog>
#include <QItemDelegate>
#include <QApplication>
#include <QIntValidator>
#include <QStandardPaths>
#include <QTreeWidgetItem>
#include <QJsonParseError>
#include <QRegExpValidator>
#include <QStringListModel>
#include <QItemSelectionModel>
#include <QAbstractTableModel>

#include "include/typedefs.h"
#include "include/tr.h"
