################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Software_configurator/configurator/Lib/liveMedia/rtcp_from_spec.c 

CPP_SRCS += \
../Software_configurator/configurator/Lib/liveMedia/AC3AudioFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/AC3AudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/AC3AudioRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/AC3AudioStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/ADTSAudioFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/ADTSAudioFileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/AMRAudioFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/AMRAudioFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/AMRAudioFileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/AMRAudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/AMRAudioRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/AMRAudioSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/AVIFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/AudioInputDevice.cpp \
../Software_configurator/configurator/Lib/liveMedia/AudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/Base64.cpp \
../Software_configurator/configurator/Lib/liveMedia/BasicUDPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/BasicUDPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/BitVector.cpp \
../Software_configurator/configurator/Lib/liveMedia/ByteStreamFileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/ByteStreamMemoryBufferSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/ByteStreamMultiFileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/DVVideoFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/DVVideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/DVVideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/DVVideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/DeviceSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/DigestAuthentication.cpp \
../Software_configurator/configurator/Lib/liveMedia/EBMLNumber.cpp \
../Software_configurator/configurator/Lib/liveMedia/FileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/FileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/FramedFileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/FramedFilter.cpp \
../Software_configurator/configurator/Lib/liveMedia/FramedSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/GSMAudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/GenericMediaServer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H261VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/H263plusVideoFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/H263plusVideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H263plusVideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/H263plusVideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H263plusVideoStreamParser.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264VideoFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264VideoFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264VideoStreamDiscreteFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264VideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264or5VideoFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264or5VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264or5VideoStreamDiscreteFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H264or5VideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H265VideoFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/H265VideoFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H265VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/H265VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/H265VideoStreamDiscreteFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/H265VideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/InputFile.cpp \
../Software_configurator/configurator/Lib/liveMedia/JPEG2000VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/JPEG2000VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/JPEGVideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/JPEGVideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/JPEGVideoSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/Locale.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3ADU.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3ADURTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3ADURTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3ADUTranscoder.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3ADUdescriptor.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3ADUinterleaving.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3AudioFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3AudioMatroskaFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3FileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3Internals.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3InternalsHuffman.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3InternalsHuffmanTable.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3StreamState.cpp \
../Software_configurator/configurator/Lib/liveMedia/MP3Transcoder.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2Demux.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2DemuxedElementaryStream.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2DemuxedServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2FileServerDemux.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoStreamDiscreteFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2IndexFromTransportStream.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamAccumulator.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFromESSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFromPESSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamIndexFile.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamMultiplexor.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamTrickModeFilter.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG2TransportUDPServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4ESVideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4ESVideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4GenericRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4GenericRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4LATMAudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4LATMAudioRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4VideoFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4VideoStreamDiscreteFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEG4VideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEGVideoStreamFramer.cpp \
../Software_configurator/configurator/Lib/liveMedia/MPEGVideoStreamParser.cpp \
../Software_configurator/configurator/Lib/liveMedia/MatroskaDemuxedTrack.cpp \
../Software_configurator/configurator/Lib/liveMedia/MatroskaFile.cpp \
../Software_configurator/configurator/Lib/liveMedia/MatroskaFileParser.cpp \
../Software_configurator/configurator/Lib/liveMedia/MatroskaFileServerDemux.cpp \
../Software_configurator/configurator/Lib/liveMedia/MatroskaFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/Media.cpp \
../Software_configurator/configurator/Lib/liveMedia/MediaSession.cpp \
../Software_configurator/configurator/Lib/liveMedia/MediaSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MediaSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/MultiFramedRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/MultiFramedRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/OggDemuxedTrack.cpp \
../Software_configurator/configurator/Lib/liveMedia/OggFile.cpp \
../Software_configurator/configurator/Lib/liveMedia/OggFileParser.cpp \
../Software_configurator/configurator/Lib/liveMedia/OggFileServerDemux.cpp \
../Software_configurator/configurator/Lib/liveMedia/OggFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/OggFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/OnDemandServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/OutputFile.cpp \
../Software_configurator/configurator/Lib/liveMedia/PassiveServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/ProxyServerMediaSession.cpp \
../Software_configurator/configurator/Lib/liveMedia/QCELPAudioRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/QuickTimeFileSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/QuickTimeGenericRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTCP.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTPInterface.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTSPClient.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTSPCommon.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTSPRegisterSender.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTSPServer.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTSPServerRegister.cpp \
../Software_configurator/configurator/Lib/liveMedia/RTSPServerSupportingHTTPStreaming.cpp \
../Software_configurator/configurator/Lib/liveMedia/RawVideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/RawVideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/SIPClient.cpp \
../Software_configurator/configurator/Lib/liveMedia/ServerMediaSession.cpp \
../Software_configurator/configurator/Lib/liveMedia/SimpleRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/SimpleRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/StreamParser.cpp \
../Software_configurator/configurator/Lib/liveMedia/StreamReplicator.cpp \
../Software_configurator/configurator/Lib/liveMedia/T140TextRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/TCPStreamSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/TextRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/TheoraVideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/TheoraVideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/VP8VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/VP8VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/VP9VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/VP9VideoRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/VideoRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/VorbisAudioRTPSink.cpp \
../Software_configurator/configurator/Lib/liveMedia/VorbisAudioRTPSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/WAVAudioFileServerMediaSubsession.cpp \
../Software_configurator/configurator/Lib/liveMedia/WAVAudioFileSource.cpp \
../Software_configurator/configurator/Lib/liveMedia/ourMD5.cpp \
../Software_configurator/configurator/Lib/liveMedia/speexaudiofilter.cpp \
../Software_configurator/configurator/Lib/liveMedia/uLawAudioFilter.cpp 

OBJS += \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/ADTSAudioFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/ADTSAudioFileSource.o \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioFileSource.o \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioSource.o \
./Software_configurator/configurator/Lib/liveMedia/AVIFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/AudioInputDevice.o \
./Software_configurator/configurator/Lib/liveMedia/AudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/Base64.o \
./Software_configurator/configurator/Lib/liveMedia/BasicUDPSink.o \
./Software_configurator/configurator/Lib/liveMedia/BasicUDPSource.o \
./Software_configurator/configurator/Lib/liveMedia/BitVector.o \
./Software_configurator/configurator/Lib/liveMedia/ByteStreamFileSource.o \
./Software_configurator/configurator/Lib/liveMedia/ByteStreamMemoryBufferSource.o \
./Software_configurator/configurator/Lib/liveMedia/ByteStreamMultiFileSource.o \
./Software_configurator/configurator/Lib/liveMedia/DVVideoFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/DVVideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/DVVideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/DVVideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/DeviceSource.o \
./Software_configurator/configurator/Lib/liveMedia/DigestAuthentication.o \
./Software_configurator/configurator/Lib/liveMedia/EBMLNumber.o \
./Software_configurator/configurator/Lib/liveMedia/FileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/FileSink.o \
./Software_configurator/configurator/Lib/liveMedia/FramedFileSource.o \
./Software_configurator/configurator/Lib/liveMedia/FramedFilter.o \
./Software_configurator/configurator/Lib/liveMedia/FramedSource.o \
./Software_configurator/configurator/Lib/liveMedia/GSMAudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/GenericMediaServer.o \
./Software_configurator/configurator/Lib/liveMedia/H261VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoStreamParser.o \
./Software_configurator/configurator/Lib/liveMedia/H264VideoFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/H264VideoFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/H264VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/H264VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/H264VideoStreamDiscreteFramer.o \
./Software_configurator/configurator/Lib/liveMedia/H264VideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoStreamDiscreteFramer.o \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/H265VideoFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/H265VideoFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/H265VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/H265VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/H265VideoStreamDiscreteFramer.o \
./Software_configurator/configurator/Lib/liveMedia/H265VideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/InputFile.o \
./Software_configurator/configurator/Lib/liveMedia/JPEG2000VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/JPEG2000VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/JPEGVideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/JPEGVideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/JPEGVideoSource.o \
./Software_configurator/configurator/Lib/liveMedia/Locale.o \
./Software_configurator/configurator/Lib/liveMedia/MP3ADU.o \
./Software_configurator/configurator/Lib/liveMedia/MP3ADURTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MP3ADURTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/MP3ADUTranscoder.o \
./Software_configurator/configurator/Lib/liveMedia/MP3ADUdescriptor.o \
./Software_configurator/configurator/Lib/liveMedia/MP3ADUinterleaving.o \
./Software_configurator/configurator/Lib/liveMedia/MP3AudioFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MP3AudioMatroskaFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MP3FileSource.o \
./Software_configurator/configurator/Lib/liveMedia/MP3Internals.o \
./Software_configurator/configurator/Lib/liveMedia/MP3InternalsHuffman.o \
./Software_configurator/configurator/Lib/liveMedia/MP3InternalsHuffmanTable.o \
./Software_configurator/configurator/Lib/liveMedia/MP3StreamState.o \
./Software_configurator/configurator/Lib/liveMedia/MP3Transcoder.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2Demux.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2DemuxedElementaryStream.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2DemuxedServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2FileServerDemux.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoStreamDiscreteFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2IndexFromTransportStream.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamAccumulator.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFromESSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFromPESSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamIndexFile.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamMultiplexor.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamTrickModeFilter.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportUDPServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4ESVideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4ESVideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4GenericRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4GenericRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4LATMAudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4LATMAudioRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4VideoFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4VideoStreamDiscreteFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEG4VideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEGVideoStreamFramer.o \
./Software_configurator/configurator/Lib/liveMedia/MPEGVideoStreamParser.o \
./Software_configurator/configurator/Lib/liveMedia/MatroskaDemuxedTrack.o \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFile.o \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFileParser.o \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFileServerDemux.o \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/Media.o \
./Software_configurator/configurator/Lib/liveMedia/MediaSession.o \
./Software_configurator/configurator/Lib/liveMedia/MediaSink.o \
./Software_configurator/configurator/Lib/liveMedia/MediaSource.o \
./Software_configurator/configurator/Lib/liveMedia/MultiFramedRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/MultiFramedRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/OggDemuxedTrack.o \
./Software_configurator/configurator/Lib/liveMedia/OggFile.o \
./Software_configurator/configurator/Lib/liveMedia/OggFileParser.o \
./Software_configurator/configurator/Lib/liveMedia/OggFileServerDemux.o \
./Software_configurator/configurator/Lib/liveMedia/OggFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/OggFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/OnDemandServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/OutputFile.o \
./Software_configurator/configurator/Lib/liveMedia/PassiveServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/ProxyServerMediaSession.o \
./Software_configurator/configurator/Lib/liveMedia/QCELPAudioRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/QuickTimeFileSink.o \
./Software_configurator/configurator/Lib/liveMedia/QuickTimeGenericRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/RTCP.o \
./Software_configurator/configurator/Lib/liveMedia/RTPInterface.o \
./Software_configurator/configurator/Lib/liveMedia/RTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/RTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/RTSPClient.o \
./Software_configurator/configurator/Lib/liveMedia/RTSPCommon.o \
./Software_configurator/configurator/Lib/liveMedia/RTSPRegisterSender.o \
./Software_configurator/configurator/Lib/liveMedia/RTSPServer.o \
./Software_configurator/configurator/Lib/liveMedia/RTSPServerRegister.o \
./Software_configurator/configurator/Lib/liveMedia/RTSPServerSupportingHTTPStreaming.o \
./Software_configurator/configurator/Lib/liveMedia/RawVideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/RawVideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/SIPClient.o \
./Software_configurator/configurator/Lib/liveMedia/ServerMediaSession.o \
./Software_configurator/configurator/Lib/liveMedia/SimpleRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/SimpleRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/StreamParser.o \
./Software_configurator/configurator/Lib/liveMedia/StreamReplicator.o \
./Software_configurator/configurator/Lib/liveMedia/T140TextRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/TCPStreamSink.o \
./Software_configurator/configurator/Lib/liveMedia/TextRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/TheoraVideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/TheoraVideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/VP8VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/VP8VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/VP9VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/VP9VideoRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/VideoRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/VorbisAudioRTPSink.o \
./Software_configurator/configurator/Lib/liveMedia/VorbisAudioRTPSource.o \
./Software_configurator/configurator/Lib/liveMedia/WAVAudioFileServerMediaSubsession.o \
./Software_configurator/configurator/Lib/liveMedia/WAVAudioFileSource.o \
./Software_configurator/configurator/Lib/liveMedia/ourMD5.o \
./Software_configurator/configurator/Lib/liveMedia/rtcp_from_spec.o \
./Software_configurator/configurator/Lib/liveMedia/speexaudiofilter.o \
./Software_configurator/configurator/Lib/liveMedia/uLawAudioFilter.o 

C_DEPS += \
./Software_configurator/configurator/Lib/liveMedia/rtcp_from_spec.d 

CPP_DEPS += \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/AC3AudioStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/ADTSAudioFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/ADTSAudioFileSource.d \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioFileSource.d \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/AMRAudioSource.d \
./Software_configurator/configurator/Lib/liveMedia/AVIFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/AudioInputDevice.d \
./Software_configurator/configurator/Lib/liveMedia/AudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/Base64.d \
./Software_configurator/configurator/Lib/liveMedia/BasicUDPSink.d \
./Software_configurator/configurator/Lib/liveMedia/BasicUDPSource.d \
./Software_configurator/configurator/Lib/liveMedia/BitVector.d \
./Software_configurator/configurator/Lib/liveMedia/ByteStreamFileSource.d \
./Software_configurator/configurator/Lib/liveMedia/ByteStreamMemoryBufferSource.d \
./Software_configurator/configurator/Lib/liveMedia/ByteStreamMultiFileSource.d \
./Software_configurator/configurator/Lib/liveMedia/DVVideoFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/DVVideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/DVVideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/DVVideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/DeviceSource.d \
./Software_configurator/configurator/Lib/liveMedia/DigestAuthentication.d \
./Software_configurator/configurator/Lib/liveMedia/EBMLNumber.d \
./Software_configurator/configurator/Lib/liveMedia/FileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/FileSink.d \
./Software_configurator/configurator/Lib/liveMedia/FramedFileSource.d \
./Software_configurator/configurator/Lib/liveMedia/FramedFilter.d \
./Software_configurator/configurator/Lib/liveMedia/FramedSource.d \
./Software_configurator/configurator/Lib/liveMedia/GSMAudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/GenericMediaServer.d \
./Software_configurator/configurator/Lib/liveMedia/H261VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/H263plusVideoStreamParser.d \
./Software_configurator/configurator/Lib/liveMedia/H264VideoFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/H264VideoFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/H264VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/H264VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/H264VideoStreamDiscreteFramer.d \
./Software_configurator/configurator/Lib/liveMedia/H264VideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoStreamDiscreteFramer.d \
./Software_configurator/configurator/Lib/liveMedia/H264or5VideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/H265VideoFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/H265VideoFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/H265VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/H265VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/H265VideoStreamDiscreteFramer.d \
./Software_configurator/configurator/Lib/liveMedia/H265VideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/InputFile.d \
./Software_configurator/configurator/Lib/liveMedia/JPEG2000VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/JPEG2000VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/JPEGVideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/JPEGVideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/JPEGVideoSource.d \
./Software_configurator/configurator/Lib/liveMedia/Locale.d \
./Software_configurator/configurator/Lib/liveMedia/MP3ADU.d \
./Software_configurator/configurator/Lib/liveMedia/MP3ADURTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MP3ADURTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/MP3ADUTranscoder.d \
./Software_configurator/configurator/Lib/liveMedia/MP3ADUdescriptor.d \
./Software_configurator/configurator/Lib/liveMedia/MP3ADUinterleaving.d \
./Software_configurator/configurator/Lib/liveMedia/MP3AudioFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MP3AudioMatroskaFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MP3FileSource.d \
./Software_configurator/configurator/Lib/liveMedia/MP3Internals.d \
./Software_configurator/configurator/Lib/liveMedia/MP3InternalsHuffman.d \
./Software_configurator/configurator/Lib/liveMedia/MP3InternalsHuffmanTable.d \
./Software_configurator/configurator/Lib/liveMedia/MP3StreamState.d \
./Software_configurator/configurator/Lib/liveMedia/MP3Transcoder.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2AudioStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2Demux.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2DemuxedElementaryStream.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2DemuxedServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2FileServerDemux.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoStreamDiscreteFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG1or2VideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2IndexFromTransportStream.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamAccumulator.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFromESSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamFromPESSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamIndexFile.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamMultiplexor.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportStreamTrickModeFilter.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG2TransportUDPServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4ESVideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4ESVideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4GenericRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4GenericRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4LATMAudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4LATMAudioRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4VideoFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4VideoStreamDiscreteFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEG4VideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEGVideoStreamFramer.d \
./Software_configurator/configurator/Lib/liveMedia/MPEGVideoStreamParser.d \
./Software_configurator/configurator/Lib/liveMedia/MatroskaDemuxedTrack.d \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFile.d \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFileParser.d \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFileServerDemux.d \
./Software_configurator/configurator/Lib/liveMedia/MatroskaFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/Media.d \
./Software_configurator/configurator/Lib/liveMedia/MediaSession.d \
./Software_configurator/configurator/Lib/liveMedia/MediaSink.d \
./Software_configurator/configurator/Lib/liveMedia/MediaSource.d \
./Software_configurator/configurator/Lib/liveMedia/MultiFramedRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/MultiFramedRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/OggDemuxedTrack.d \
./Software_configurator/configurator/Lib/liveMedia/OggFile.d \
./Software_configurator/configurator/Lib/liveMedia/OggFileParser.d \
./Software_configurator/configurator/Lib/liveMedia/OggFileServerDemux.d \
./Software_configurator/configurator/Lib/liveMedia/OggFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/OggFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/OnDemandServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/OutputFile.d \
./Software_configurator/configurator/Lib/liveMedia/PassiveServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/ProxyServerMediaSession.d \
./Software_configurator/configurator/Lib/liveMedia/QCELPAudioRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/QuickTimeFileSink.d \
./Software_configurator/configurator/Lib/liveMedia/QuickTimeGenericRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/RTCP.d \
./Software_configurator/configurator/Lib/liveMedia/RTPInterface.d \
./Software_configurator/configurator/Lib/liveMedia/RTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/RTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/RTSPClient.d \
./Software_configurator/configurator/Lib/liveMedia/RTSPCommon.d \
./Software_configurator/configurator/Lib/liveMedia/RTSPRegisterSender.d \
./Software_configurator/configurator/Lib/liveMedia/RTSPServer.d \
./Software_configurator/configurator/Lib/liveMedia/RTSPServerRegister.d \
./Software_configurator/configurator/Lib/liveMedia/RTSPServerSupportingHTTPStreaming.d \
./Software_configurator/configurator/Lib/liveMedia/RawVideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/RawVideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/SIPClient.d \
./Software_configurator/configurator/Lib/liveMedia/ServerMediaSession.d \
./Software_configurator/configurator/Lib/liveMedia/SimpleRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/SimpleRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/StreamParser.d \
./Software_configurator/configurator/Lib/liveMedia/StreamReplicator.d \
./Software_configurator/configurator/Lib/liveMedia/T140TextRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/TCPStreamSink.d \
./Software_configurator/configurator/Lib/liveMedia/TextRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/TheoraVideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/TheoraVideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/VP8VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/VP8VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/VP9VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/VP9VideoRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/VideoRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/VorbisAudioRTPSink.d \
./Software_configurator/configurator/Lib/liveMedia/VorbisAudioRTPSource.d \
./Software_configurator/configurator/Lib/liveMedia/WAVAudioFileServerMediaSubsession.d \
./Software_configurator/configurator/Lib/liveMedia/WAVAudioFileSource.d \
./Software_configurator/configurator/Lib/liveMedia/ourMD5.d \
./Software_configurator/configurator/Lib/liveMedia/speexaudiofilter.d \
./Software_configurator/configurator/Lib/liveMedia/uLawAudioFilter.d 


# Each subdirectory must supply rules for building sources it contributes
Software_configurator/configurator/Lib/liveMedia/%.o: ../Software_configurator/configurator/Lib/liveMedia/%.cpp Software_configurator/configurator/Lib/liveMedia/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Software_configurator/configurator/Lib/liveMedia/%.o: ../Software_configurator/configurator/Lib/liveMedia/%.c Software_configurator/configurator/Lib/liveMedia/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


