#!/usr/bin/bash
#cd SOFT/Github/GIT/16_WEB_ARHIV/create_content_for_web/build &&  cmake -DCMAKE_BUILD_TYPE=Release .. && make -j8 all
cd SOFT/Github/GIT/16_WEB_ARHIV/create_content_for_web/build && rm CMakeCache.txt && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j8 all
