#!/usr/bin/bash
docker run --name=createwebcontent -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -v /home/evg/Ниокр-Актуальные_документы:/home/evg/SOFT/Github/GIT/16_WEB_ARHIV/Ниокр-Актуальные_документы 8evgeny/createwebcontent
docker cp createwebcontent:/home/evg/SOFT/Github/GIT/16_WEB_ARHIV /home/evg  
docker stop  createwebcontent
docker rm  createwebcontent
