#!/usr/bin/bash
docker run --name=createwebcontent -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro -v /home/evg/WG/Ниокр-Актуальные\ документы:/home/evg/SOFT/Github/GIT/16_WEB_ARHIV/Ниокр-Актуальные_документы 8evgeny/createwebcontent
docker cp createwebcontent:/home/evg/SOFT/Github/GIT/16_WEB_ARHIV/CONTENT /home/evg/16_WEB_ARHIV 
docker stop  createwebcontent
docker rm  createwebcontent
