#pragma once

#if defined(NETWORK_CONFIGURING_DIALOG_LIBRARY)
    #define NETWORK_CONFIGURING_DIALOG_SHARED_EXPORT Q_DECL_EXPORT
#else
    #define NETWORK_CONFIGURING_DIALOG_SHARED_EXPORT Q_DECL_IMPORT
#endif

