#pragma once

#if defined(ACTIVATE_CONTROL_LINES_DIALOG_LIBRARY)
    #define ACTIVATE_CONTROL_LINES_DIALOG_SHARED_EXPORT Q_DECL_EXPORT
#else
    #define ACTIVATE_CONTROL_LINES_DIALOG_SHARED_EXPORT Q_DECL_IMPORT
#endif
