#!/bin/bash
psql -d niokrDB -U postgres
psql --command "CREATE USER evg WITH PASSWORD '123';" 
psql --command "CREATE DATABASE niokrDB;"
psql --command "CREATE TABLE distributors (did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name varchar(40) NOT NULL CHECK (name <> ''));"
psql --command "GRANT ALL PRIVILEGES ON DATABASE niokrDB to evg;"
psql --command "\q;"  
psql -U evg -d niokrDB -f /var/lib/postgresql/backup.sql

exit
