#!/bin/bash
psql -d niokrDB -U postgres
psql -c "CREATE TABLE IF NOT EXISTS distributors (did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name varchar(40) NOT NULL CHECK (name <> ''));"
exit
