#!/bin/bash
psql -d niokrDB -U postgres
psql -c "CREATE ROLE evg WITH LOGIN;"
psql -c "CREATE DATABASE niokrDB;"
psql -c "GRANT ALL PRIVILEGES ON DATABASE niokrDB to evg;"
#psql -c "CREATE TABLE IF NOT EXISTS distributors (did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,name varchar(40) NOT NULL CHECK (name <> ''));"
psql -U evg -d niokrDB -f /var/lib/postgresql/backup.sql
psql -c "\q;"
exit
