version: "3.3"
services:
  postgres:
    image: postgres:13.3
    container_name:  habr-pg-13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    #volumes:
    #- postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
