#pragma once

#if defined(SENDCONFIGURATION_DIALOG_LIBRARY)
    #define SENDCONFIGURATION_DIALOG_SHARED_EXPORT Q_DECL_EXPORT
#else
    #define SENDCONFIGURATION_DIALOG_SHARED_EXPORT Q_DECL_IMPORT
#endif

